name: Build Android App

on:
  push:
    branches:
      - main  # Trigger the build on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the build for pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-dev build-essential git libssl-dev zlib1g-dev
        python -m pip install --upgrade pip
        pip install buildozer

    - name: Install Android NDK, SDK, and dependencies
      run: |
        sudo apt install -y openjdk-8-jdk
        wget https://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip -P $HOME
        unzip $HOME/android-ndk-r21d-linux-x86_64.zip -d $HOME
        export ANDROID_NDK=$HOME/android-ndk-r21d
        echo "export ANDROID_NDK=$HOME/android-ndk-r21d" >> $GITHUB_ENV
        export ANDROID_SDK=$HOME/android-sdk-linux
        echo "export ANDROID_SDK=$HOME/android-sdk-linux" >> $GITHUB_ENV
        # Accept Android SDK licenses
        yes | $ANDROID_SDK/tools/bin/sdkmanager --licenses

    - name: Build with Buildozer
      run: |
        buildozer android debug deploy run

    - name: Upload APK to GitHub Releases
      if: success()
      uses: softprops/action-gh-release@v1
      with:
        files: "bin/*.apk"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
